# See 
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# for ideas.

# Project information
site_name: "swift2 - python package"
site_url: https://csiro-hydroinformatics.github.io/swift-py-doc/ # required by mkdocs-llmstxt
# site_url: https://squidfunk.github.io/mkdocs-material/
site_author: "Jean-Michel Perraud"
site_description: >-
  Bindings to access the SWIFT2 libraries, from Python.

# Repository
repo_name: csiro-hydroinformatics/swift-py-doc
repo_url: https://github.com/csiro-hydroinformatics/swift-py-doc/
# repo_name: bitbucket/SWIFT2
# repo_url: https://bitbucket.csiro.au/projects/SF/repos/swift

docs_dir: './docs'

# Copyright
copyright: Copyright &copy; 2016 - 2025 CSIRO

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  # name: "readthedocs"
  name: "material"
  logo: images/ensembles.png
  #icon:
  #  logo: material/cube
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  # Default values, taken from mkdocs_theme.yml
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: google
  # minify seems advanced. https://squidfunk.github.io/mkdocs-material/customization/#theme-development
  # https://github.com/byrnereese/mkdocs-minify-plugin May 2025 try to use. May now be a default anyway in mkdocs-material
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - llmstxt:
      markdown_description: Python package for ensemble streamflow forecasting. It can equally be used in non-ensemble simulation mode for other, “traditional” semi-distributed hydrologic modelling.
      full_output: llms-ctx.txt
      sections:
        API documentation:
          - classes.md
          - common.md
          - const.md
          - doc_helper.md
          - helpers.md
          - internal.md
          - model_definitions.md
          - parameteriser.md
          - play_record.md
          - proto.md
          - prototypes.md
          - simulation.md
          - statistics.md
          - system.md
          - utils.md
          - vis.md
        # including jpt notebooks seems not to work intuitively, not yet (fair enough!)
        # Examples:
        #   - notebooks/getting_started.ipynb
        #   - notebooks/meta_parameters.ipynb
        #   - notebooks/ensemble_model_runs.ipynb
        #   - notebooks/calibration_initial_states.ipynb
        #   - notebooks/calibrate_multisite.ipynb
        #   - notebooks/reservoir_geometry.ipynb
        #   - notebooks/calibrate_subcatchments.ipynb
        #   - notebooks/log_likelihood.ipynb
        #   - notebooks/muskingum_multilink_calibration.ipynb
        #   - notebooks/error_correction_four_stages.ipynb
  - mkdocs-jupyter


# Extensions
markdown_extensions:
  - abbr
  - admonition
  - callouts
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
     anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.keys
  # - pymdownx.magiclink:
  #    repo_url_shorthand: true
  #    user: csiro-hydroinformatics
  #    repo: pyrefcount
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  # - Code Documentation: code-reference.md
  - Submodules: 
    - classes: classes.md
    - common: common.md
    - const: const.md
    - doc_helper: doc_helper.md
    - helpers: helpers.md
    - internal: internal.md
    - model_definitions: model_definitions.md
    - parameteriser: parameteriser.md
    - play_record: play_record.md
    - proto: proto.md
    - prototypes: prototypes.md
    - simulation: simulation.md
    - statistics: statistics.md
    - system: system.md
    - utils: utils.md
    - vis: vis.md
  - Notebooks:
    - getting_started: notebooks/getting_started.ipynb
    - meta_parameters: notebooks/meta_parameters.ipynb
    - ensemble_model_runs: notebooks/ensemble_model_runs.ipynb
    - calibration_initial_states: notebooks/calibration_initial_states.ipynb
    - calibrate_multisite: notebooks/calibrate_multisite.ipynb
    - reservoir_geometry: notebooks/reservoir_geometry.ipynb
    - calibrate_subcatchments: notebooks/calibrate_subcatchments.ipynb
    - log_likelihood: notebooks/log_likelihood.ipynb
    - muskingum_multilink_calibration: notebooks/muskingum_multilink_calibration.ipynb
    - error_correction_four_stages: notebooks/error_correction_four_stages.ipynb
  - Appendix:
    - Tech Notes: tech_notes.md

